basic_app/urls.py
from django.conf.urls import url
from basic_app import views



app_name="basic_app"

urlpatterns=[
    url(r'^register/$',views.register,name="registration"),
    url(r'^$',views.index,name="index"),
    url(r'^user_login/$', views.user_login, name="user_login"),

]

learning_user_auth/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name="index"),
    url(r'^basicapp/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout,name="logout"),
]

basic_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')




class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from basic_app import forms
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method=='POST':
        user_form=forms.UserForm(data=request.POST)
        profile_form=forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=forms.UserForm()
        profile_form=forms.UserProfileInfoForm()


    return render(request,'basic_app/registration.html',{'user_form':user_form,
                                                         'profile_form':profile_form,
                                                         'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed")
            print("Username : {} and password : {}".format(username,password))
            return HttpResponse("Invalid Login")

    else:
        return render(request,'basic_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %}{% endblock %}</title>
    <style>

    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="navbar-brand" href="{% url 'basic_app:index' %} ">DJANGO</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'basic_app:registration' %}">Register</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </nav>

        <div class="container">
            {% block body_block %}

            {% endblock %}
        </div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'basic_app:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username : </label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password : </label>
            <input type="password" name="password">
            <input type="submit" value="Login">

        </form>
    </div>
{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Registration
{% endblock %}
{% block body_block %}
    <div class="jumbotron">
    {% if registered %}
        <h1>Thank You for registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}

    </div>
{% endblock %}